version: '3.9'
services:
  courses-server:
    image: operrathor/courses-server:1.0.0
    environment:
      - NODE_ENV=production
    labels:
      - traefik.http.routers.courses-server.rule=PathPrefix(`/api`)
    restart: always
  courses-client:
    image: operrathor/courses-client:1.0.0
    environment:
      - NODE_ENV=production
      - REACT_APP_API_BASE_URL=/api
    labels:
      - traefik.http.routers.courses-client.rule=PathPrefix(`/`)
    restart: always
  courses-proxy:
    image: traefik:v2.5
    command:
      - --providers.docker
      - --entrypoints.web.address=:${COURSES_PROXY_PORT}
    ports:
      - "${COURSES_PROXY_PORT}:${COURSES_PROXY_PORT}"
    restart: always
    volumes:
      - ${DOCKER_SOCK}:/var/run/docker.sock
